
MACRO(ENABLE_THREADS TARGET)
    IF(CMAKE_THREAD_LIBS_INIT)
    SET_TARGET_PROPERTIES(${TARGET}
        PROPERTIES LINK_FLAGS ${CMAKE_THREAD_LIBS_INIT})
    ELSE(CMAKE_THREAD_LIBS_INIT)
        MESSAGE("Threading library not found!")
    ENDIF(CMAKE_THREAD_LIBS_INIT)
ENDMACRO(ENABLE_THREADS)

MACRO(COMPILE_WITH_THREAD_SAFETY TARGET)
    SET_TARGET_PROPERTIES(${TARGET}
        PROPERTIES COMPILE_FLAGS "-DNABOO_THREAD_SAFE")
ENDMACRO(COMPILE_WITH_THREAD_SAFETY)

FIND_LIBRARY(LIB_TCMALLOC tcmalloc)
IF(LIB_TCMALLOC)
    MESSAGE("Linking with tcmalloc ...")
    MESSAGE("Set the environment variable HEAPCHECK=normal to enable heap check.")
ELSE(LIB_TCMALLOC)
    MESSAGE("Linking without tcmalloc ...")
ENDIF(LIB_TCMALLOC)

# Try to find tcmalloc for heap checking and profiling
MACRO(MAYBE_LINK_TCMALLOC TARGET)
    IF(LIB_TCMALLOC)
        ENABLE_THREADS(${TARGET})
        TARGET_LINK_LIBRARIES(${TARGET} ${LIB_TCMALLOC})
    ENDIF(LIB_TCMALLOC)
ENDMACRO(MAYBE_LINK_TCMALLOC)

